/* eslint-disable import/prefer-default-export */
export const gentner = {
  1: {
    first: 'Zachary',
    middle: 'Norman',
    surname: 'Gentner',
    maiden: '',
    birth: '1992',
    death: '',
    photo:
      'https://gravatar.com/userimage/79746757/3c912a1d5fb907c633bfb0842725cf2a.jpeg?size=256',
    ancestry: '352320388648',
    familysearch: 'L2Y8-T2J',
    findagrave: '',
  },
  2: {
    first: 'Todd',
    middle: 'William',
    surname: 'Gentner',
    maiden: '',
    birth: '1965',
    death: '2021',
    photo:
      'https://tributecenteronline.s3-accelerate.amazonaws.com/Obituaries/25770932/Thumbnail.jpg',
    ancestry: '352320388658',
    familysearch: 'L2YL-R5W',
    findagrave: '232743360',
  },
  3: {
    first: 'Debra',
    middle: 'Diane',
    surname: 'Gentner',
    maiden: 'Chatfield',
    birth: '1968',
    death: '',
    ancestry: '352320388669',
    familysearch: 'L2YL-RYV',
    findagrave: '242621477',
  },
  4: {
    first: 'Norman',
    middle: 'Russell',
    surname: 'Gentner',
    maiden: '',
    birth: '1941',
    death: '2025',
    ancestry: '352320388755',
    familysearch: 'L2YL-YL7',
    findagrave: '175284135',
  },
  5: {
    first: 'Betty',
    middle: 'Rae',
    surname: 'Gentner',
    maiden: 'Helm',
    birth: '1942',
    death: '2002',
    ancestry: '352320388741',
    familysearch: 'L2YX-JLJ',
    findagrave: '36924455',
  },
  6: {
    first: 'Robert',
    middle: 'Dennis',
    surname: 'Chatfield',
    maiden: '',
    birth: '1945',
    death: '',
    ancestry: '352320388711',
    familysearch: 'L2YL-TSW',
    findagrave: '242408188',
  },
  7: {
    first: 'Diane',
    middle: 'Joyce',
    surname: 'Chatfield',
    maiden: 'MacKenzie',
    birth: '1945',
    death: '2021',
    ancestry: '352320388725',
    familysearch: 'L2YL-TQ5',
    findagrave: '220745410',
  },
  8: {
    first: 'Herbert',
    middle: 'William',
    surname: 'Gentner',
    maiden: '',
    birth: '1910',
    death: '1983',
    ancestry: '',
    familysearch: 'L2YX-J24',
    findagrave: '36924469',
  },
  9: {
    first: 'Bessie',
    middle: 'Dorothy',
    surname: 'Gentner',
    maiden: 'Willis',
    birth: '1909',
    death: '1982',
    ancestry: '',
    familysearch: 'L2YX-JG9',
    findagrave: '36924467',
  },
  10: {
    first: 'Elmer',
    middle: 'Martin',
    surname: 'Helm',
    maiden: '',
    birth: '1914',
    death: '2001',
    ancestry: '',
    familysearch: 'L2YX-JK5',
    findagrave: '71723715',
  },
  11: {
    first: 'Marian',
    middle: 'Louise',
    surname: 'Helm',
    maiden: 'Hoffman',
    birth: '1919',
    death: '1982',
    ancestry: '',
    familysearch: 'L2YX-JL5',
    findagrave: '71723742',
  },
  12: {
    first: 'Otis',
    middle: 'Lavern',
    surname: 'Chatfield',
    maiden: '',
    birth: '1914',
    death: '1996',
    ancestry: '',
    familysearch: 'LL46-YTZ',
    findagrave: '161872913',
  },
  13: {
    first: 'Shirley',
    middle: 'Eileen',
    surname: 'Chatfield',
    maiden: 'Howard',
    birth: '1919',
    death: '2019',
    ancestry: '',
    familysearch: 'L2YL-YXS',
    findagrave: '175288090',
  },
  14: {
    first: 'John',
    middle: 'Kenneth',
    surname: 'MacKenzie',
    maiden: '',
    birth: '1913',
    death: '1998',
    ancestry: '',
    familysearch: 'L2YX-JLC',
    findagrave: '175273157',
  },
  15: {
    first: 'Alice',
    middle: 'Virginia',
    surname: 'MacKenzie',
    maiden: 'Dierkens',
    birth: '1923',
    death: '1999',
    ancestry: '',
    familysearch: 'L2YX-JGC',
    findagrave: '175273302',
  },
  16: {
    first: 'William',
    middle: 'Anton',
    surname: 'Gentner',
    maiden: '',
    birth: '1884',
    death: '1973',
    ancestry: '',
    familysearch: 'L2YL-GRJ',
    findagrave: '183091939',
  },
  17: {
    first: 'Elizabeth',
    middle: 'Ann',
    surname: 'Gentner',
    maiden: 'Gottschalk',
    birth: '1886',
    death: '1968',
    ancestry: '',
    familysearch: 'L2YL-GYM',
    findagrave: '183092064',
  },
  18: {
    first: 'William',
    middle: 'Hamilton',
    surname: 'Willis',
    maiden: '',
    birth: '1875',
    death: '1951',
    ancestry: '',
    familysearch: 'L2YL-GBC',
    findagrave: '232417173',
  },
  19: {
    first: 'Mary',
    middle: 'Ann',
    surname: 'Willis',
    maiden: 'MacDonald',
    birth: '1881',
    death: '1971',
    ancestry: '',
    familysearch: 'L2YL-P9W',
    findagrave: '36924473',
  },
  20: {
    first: 'Louis',
    middle: 'Henry',
    surname: 'Helm',
    maiden: '',
    birth: '1882',
    death: '1961',
    ancestry: '',
    familysearch: 'L2YL-P36',
    findagrave: '242639144',
  },
  21: {
    first: 'Mary',
    middle: 'Ann',
    surname: 'Helm',
    maiden: 'Fritsch',
    birth: '1884',
    death: '1968',
    ancestry: '',
    familysearch: 'L2YL-PQR',
    findagrave: '242639735',
  },
  22: {
    first: 'William',
    middle: 'August',
    surname: 'Hoffman',
    maiden: '',
    birth: '1887',
    death: '1967',
    ancestry: '',
    familysearch: 'L2YL-P7J',
    findagrave: '71723842',
  },
  23: {
    first: 'Bernice',
    middle: 'Ione',
    surname: 'Hoffman',
    maiden: 'Wickwire',
    birth: '1968',
    death: '1928',
    ancestry: '',
    familysearch: 'L2YL-PWX',
    findagrave: '206012900',
  },
  24: {
    first: 'Warren',
    middle: 'Judson',
    surname: 'Chatfield',
    maiden: '',
    birth: '1884',
    death: '1956',
    ancestry: '',
    familysearch: 'LHWP-2PF',
    findagrave: '70659542',
  },
  25: {
    first: 'Gerna',
    middle: 'Lenora',
    surname: 'Chatfield',
    maiden: 'Brackney',
    birth: '1885',
    death: '1964',
    ancestry: '',
    familysearch: '9KS3-7S1',
    findagrave: '70659583',
  },
  26: {
    first: 'Francis',
    middle: 'Benjamin',
    surname: 'Howard',
    maiden: '',
    birth: '1891',
    death: '1970',
    ancestry: '',
    familysearch: '9DCS-RQ6',
    findagrave: '42556789',
  },
  27: {
    first: 'Ruth',
    middle: 'Magdalena',
    surname: 'Horward',
    maiden: 'Richardson',
    birth: '1892',
    death: '1964',
    ancestry: '',
    familysearch: 'L2P8-2PJ',
    findagrave: '41473520',
  },
  28: {
    first: 'John',
    middle: 'Kenneth',
    surname: 'MacKenzie',
    maiden: '',
    birth: '1886',
    death: '1933',
    ancestry: '',
    familysearch: 'L2BM-23X',
    findagrave: '161874921',
  },
  29: {
    first: 'Catherine',
    middle: 'Boyd',
    surname: 'MacKenzie',
    maiden: 'Harkins',
    birth: '1886',
    death: '1928',
    ancestry: '',
    familysearch: 'L2BM-2C9',
    findagrave: '161874893',
  },
  30: {
    first: 'Julius',
    middle: 'Camiel',
    surname: 'Dierkens',
    maiden: '',
    birth: '1890',
    death: '1977',
    ancestry: '',
    familysearch: 'L2YG-M9S',
    findagrave: '58786526',
  },
  31: {
    first: 'Reba',
    middle: 'H.',
    surname: 'Dierkens',
    maiden: 'Ponton',
    birth: '1905',
    death: '1967',
    ancestry: '',
    familysearch: 'L2YG-M7W',
    findagrave: '58789600',
  },
  32: {
    first: 'Stephen',
    middle: '',
    maiden: '',
    surname: 'Gentner',
    birth: '1849',
    death: '1938',
    ancestry: '352320388889',
    familysearch: 'L4W5-5DW',
    findagrave: '',
  },
  33: {
    first: 'Barbara',
    middle: '',
    maiden: 'Artman',
    surname: 'Gentner',
    birth: '1860',
    death: '1952',
    ancestry: '352320388904',
    familysearch: 'L4W5-5D8',
    findagrave: '',
  },
  34: {
    first: 'Frederick',
    middle: '',
    maiden: '',
    surname: 'Gottschalk',
    birth: '1865',
    death: '1918',
    ancestry: '352320388847',
    familysearch: 'GFPY-L4G',
    findagrave: '111155393',
  },
  35: {
    first: 'Freda',
    middle: '',
    maiden: 'Baer',
    surname: 'Gottschalk',
    birth: '1868',
    death: '1952',
    ancestry: '352320388860',
    familysearch: 'L459-GGZ',
    findagrave: '248422010',
  },
  36: {
    first: 'Edward',
    middle: '',
    maiden: '',
    surname: 'Willis',
    birth: '1868',
    death: '1952',
    ancestry: '',
    familysearch: 'LBJB-FBC',
    findagrave: '197782391',
  },
  37: {
    first: 'Sarah',
    middle: '',
    maiden: 'Adams',
    surname: 'Willis',
    birth: '1839',
    death: '1925',
    ancestry: '',
    familysearch: 'L1NQ-WD7',
    findagrave: '215867241',
  },
  38: {
    first: 'Angus',
    middle: '',
    maiden: '',
    surname: 'MacDonald',
    birth: '1846',
    death: '1943',
    ancestry: '',
    familysearch: 'GSFX-MC8',
    findagrave: '',
  },
  39: {
    first: 'Annie',
    middle: '',
    maiden: 'MacLean',
    surname: 'MacDonald',
    birth: '1859',
    death: '1921',
    ancestry: '',
    familysearch: 'GSFX-CFD',
    findagrave: '',
  },
  40: {
    first: 'John',
    middle: '',
    maiden: '',
    surname: 'Helm',
    birth: '1848',
    death: '',
    ancestry: '',
    familysearch: 'K4TF-RMZ',
    findagrave: '242623949',
  },
  41: {
    first: 'Henrietta',
    middle: '',
    maiden: 'Yarbrough',
    surname: 'Helm',
    birth: '1854',
    death: '1915',
    ancestry: '',
    familysearch: 'KZHS-V7H',
    findagrave: '61264189',
  },
  42: {
    first: 'Martin',
    middle: '',
    maiden: '',
    surname: 'Fritsch',
    birth: '1848',
    death: '1925',
    ancestry: '',
    familysearch: 'GS3B-K2N',
    findagrave: '110655202',
  },
  43: {
    first: 'Margaret',
    middle: '',
    maiden: 'Friedhoff',
    surname: 'Fritsch',
    birth: '1848',
    death: '1928',
    ancestry: '',
    familysearch: 'GS3B-VSD',
    findagrave: '110655098',
  },
  44: {
    first: 'Malter',
    middle: 'D.',
    maiden: '',
    surname: 'Hoffman',
    birth: '1856',
    death: '1927',
    ancestry: '',
    familysearch: 'LVY6-HT4',
    findagrave: '169440019',
  },
  45: {
    first: 'Amelia',
    middle: '',
    maiden: 'Kodelmann',
    surname: 'Hoffman',
    birth: '1855',
    death: '1925',
    ancestry: '',
    familysearch: 'LVY6-CML',
    findagrave: '169440018',
  },
  46: {
    first: 'Herbert',
    middle: 'A',
    maiden: '',
    surname: 'Wickwire',
    birth: '1870',
    death: '1953',
    ancestry: '',
    familysearch: '9D4G-NW8',
    findagrave: '193294342',
  },
  47: {
    first: 'Sarah',
    middle: 'Ann',
    maiden: 'Cook',
    surname: 'Wickwire',
    birth: '1876',
    death: '1930',
    ancestry: '',
    familysearch: 'LTBM-X5C',
    findagrave: '206012878',
  },
  48: {
    first: 'Davis',
    middle: 'Smith',
    maiden: '',
    surname: 'Chatfield',
    birth: '1847',
    death: '1920',
    ancestry: '',
    familysearch: 'LHWP-LSJ',
    findagrave: '43483076',
  },
  49: {
    first: 'Laura',
    middle: 'Elizabeth',
    maiden: 'Chase',
    surname: 'Chatfield',
    birth: '1851',
    death: '1924',
    ancestry: '',
    familysearch: '9XS9-S6J',
    findagrave: '43483089',
  },
  50: {
    first: 'David',
    middle: '',
    maiden: '',
    surname: 'Brackney',
    birth: '1850',
    death: '1934',
    ancestry: '',
    familysearch: 'K4KS-LWX',
    findagrave: '52973572',
  },
  51: {
    first: 'Hannah',
    middle: 'E',
    maiden: 'Jackson',
    surname: 'Brackney',
    birth: '1851',
    death: '1897',
    ancestry: '',
    familysearch: 'K4L2-23F',
    findagrave: '48572615',
  },
  52: {
    first: 'Benjamin',
    middle: 'C',
    maiden: '',
    surname: 'Howard',
    birth: '1844',
    death: '1904',
    ancestry: '',
    familysearch: 'LDD5-2T1',
    findagrave: '27156010',
  },
  53: {
    first: 'Esther',
    middle: 'Ann',
    maiden: 'Durkee',
    surname: 'Howard',
    birth: '1849',
    death: '1926',
    ancestry: '',
    familysearch: 'LDD5-LKT',
    findagrave: '27156017',
  },
  54: {
    first: 'Frank',
    middle: 'C',
    maiden: '',
    surname: 'Richardson',
    birth: '1866',
    death: '1927',
    ancestry: '',
    familysearch: '9FWM-K86',
    findagrave: '79955298',
  },
  55: {
    first: 'Mary',
    middle: 'Ann',
    maiden: 'Schnierla',
    surname: 'Howard',
    birth: '1869',
    death: '1954',
    ancestry: '',
    familysearch: '9FWM-K8V',
    findagrave: '79955330',
  },
  56: {
    first: 'Kenneth',
    middle: '',
    maiden: '',
    surname: 'MacKenzie',
    birth: '1855',
    death: '1903',
    ancestry: '',
    familysearch: 'M914-S3V',
    findagrave: '',
  },
  57: {
    first: 'Mary',
    middle: 'Ann',
    maiden: 'MacLeod',
    surname: 'MacKenzie',
    birth: '1860',
    death: '1895',
    ancestry: '',
    familysearch: 'G43S-BDJ',
    findagrave: '',
  },
  58: {
    first: 'Patrick',
    middle: '',
    maiden: '',
    surname: 'Harkins',
    birth: '1857',
    death: '',
    ancestry: '',
    familysearch: '9W9F-9CZ',
    findagrave: '',
  },
  // 59: {},
  // 60: {},
  // 61: {},
  // 62: {},
  // 63: {},
};

export const colson = {
  1: {
    first: 'Maggie',
    middle: 'Katherine',
    surname: 'Gentner',
    maiden: 'Colson',
    birth: '1999',
    death: '',
    ancestry: '',
    familysearch: 'GS6K-VN4',
    findagrave: '',
  },
};
